### ISSUE TITLE
Client crashes when somebody else break signs

### ISSUE THREAD

**Issue by Ghostlyr** [hanakocz/Railcraft-Cosmetic-Additions#12]
Previously received an ClassCastException, and now with #8 fix get a new exception

```
java.lang.NullPointerException: Registering texture
at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:63)
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:29)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:89)
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:45)
	at mods.railcraft_cos.common.tileentities.TESRSignBasic.func_147500_a(TESRSignBasic.java:18)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:766)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1557)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1305)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
```

MC 1.7.10
Forge 1614
RailcraftCosmetics compiled from latest source code

**Comment by hanakocz** [comment]
Oh well if you can avoid such a situation, it would be good for now. (also would be cool if you mention the situation that led to this error)  I can look into it more, but my main focus is now at 1.10.2 version, where I rewrote a lot of things (however not yet signs, that is still planned soon), but such a rewrite was planned - especially for signs - also for 1.7.10, thus I would use that to update 1.7.10 version as well. Because after all , those signs are kinda messy, I would rather have them more flexible similar to vanilla signs (sticking to wallls etc), then those problems would get fixed by themself , probably :)

**Comment by Ghostlyr** [comment]
This occurred after a player who was nearby, began to break and place signs from mod. It is not always reproduced, but too often, to avoid this situation.
